/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: scripts/generate-playground-registry.js
 * Generated at: 2025-12-29T14:26:04.361Z
 *
 * To regenerate, run: npm run generate:playground
 */

import React from 'react';

// ============================================================
// AUTO-GENERATED IMPORTS (254 components)
// ============================================================
import { AssistantBubble } from '../components/assistant/AssistantBubble';
import { AnimatedClouds } from '../components/background/AnimatedCloud';
import { Flowers } from '../components/background/Flowers';
import { ForestBackground } from '../components/background/ForestBackground';
import { Hills } from '../components/background/Hills';
import { Mountains } from '../components/background/Mountains';
import { Sun } from '../components/background/Sun';
import { Trees } from '../components/background/Trees';
import { Dragonfly } from '../components/background/animals/Dragonfly';
import { BalanceGameScreen } from '../games/04-balance/screens/BalanceGameScreen';
import { BalanceHanoiIntroScreen } from '../games/04-balance/screens/BalanceHanoiIntroScreen';
import { BalanceIntroScreen } from '../games/04-balance/screens/BalanceIntroScreen';
import { BalanceScale } from '../games/04-balance/components/BalanceScale';
import { DrHibou } from '../games/04-balance/components/DrHibou';
import { EquivalenceJournal } from '../games/04-balance/components/EquivalenceJournal';
import { LevelSelector } from '../games/04-balance/components/LevelSelector';
import { SandboxMode } from '../games/04-balance/components/SandboxMode';
import { WeightObject } from '../games/04-balance/components/WeightObject';
import { CardDetailModal } from '../components/collection/CardDetailModal';
import { CardUnlockScreen } from '../components/collection/CardUnlockScreen';
import { CategoryTabs } from '../components/collection/CategoryTabs';
import { CollectionBook } from '../components/collection/CollectionBook';
import { CollectionCard } from '../components/collection/CollectionCard';
import { CollectionPage } from '../components/collection/CollectionPage';
import { BackButton } from '../components/common/BackButton';
import { Button } from '../components/common/Button';
import { CardFlip } from '../components/common/CardFlip';
import { Confetti } from '../components/common/Confetti';
import { GameActionButtons } from '../components/common/GameActionButtons';
import { GameIntroTemplate } from '../components/common/GameIntroTemplate';
import { GameModal } from '../components/common/GameModal';
import { HintButton } from '../components/common/HintButton';
import { IconButton } from '../components/common/IconButton';
import { MascotBubble } from '../components/common/MascotBubble';
import { PageContainer } from '../components/common/PageContainer';
import { ParentGate } from '../components/common/ParentGate';
import { PerformanceStats } from '../components/common/PerformanceStats';
import { ProgressIndicator } from '../components/common/ProgressIndicator';
import { ScreenBackground } from '../components/common/ScreenBackground';
import { ScreenHeader } from '../components/common/ScreenHeader';
import { VictoryCard } from '../components/common/VictoryCard';
import { VictoryOverlayBase } from '../components/common/VictoryOverlayBase';
import { AdventureScene } from '../games/06-conteur-curieux/assets/illustrations/AdventureScene';
import { AnswerButton } from '../games/06-conteur-curieux/components/AnswerButton';
import { AudioPlayer } from '../games/06-conteur-curieux/components/AudioPlayer';
import { CollectibleCard } from '../games/06-conteur-curieux/components/CollectibleCard';
import { ConteurIntroScreen } from '../games/06-conteur-curieux/screens/ConteurIntroScreen';
import { ConteurParentScreen } from '../games/06-conteur-curieux/screens/ConteurParentScreen';
import { ConteurQuestionsScreen } from '../games/06-conteur-curieux/screens/ConteurQuestionsScreen';
import { ConteurRecordingScreen } from '../games/06-conteur-curieux/screens/ConteurRecordingScreen';
import { ConteurStoryScreen } from '../games/06-conteur-curieux/screens/ConteurStoryScreen';
import { ConteurVictoryScreen } from '../games/06-conteur-curieux/screens/ConteurVictoryScreen';
import { FamilyScene } from '../games/06-conteur-curieux/assets/illustrations/FamilyScene';
import { FeedbackOverlay } from '../games/06-conteur-curieux/components/FeedbackOverlay';
import { FilterTabs } from '../games/06-conteur-curieux/components/FilterTabs';
import { ForestScene } from '../games/06-conteur-curieux/assets/illustrations/ForestScene';
import { FriendshipScene } from '../games/06-conteur-curieux/assets/illustrations/FriendshipScene';
import { LibraryBackground } from '../games/06-conteur-curieux/components/LibraryBackground';
import { MagicScene } from '../games/06-conteur-curieux/assets/illustrations/MagicScene';
import { ModeSelectionModal } from '../games/06-conteur-curieux/components/ModeSelectionModal';
import { PlumeMascot } from '../games/06-conteur-curieux/components/PlumeMascot';
import { QuestionCard } from '../games/06-conteur-curieux/components/QuestionCard';
import { RadarChart } from '../games/06-conteur-curieux/components/RadarChart';
import { RaysEffect } from '../games/06-conteur-curieux/components/RaysEffect';
import { RecordingsList } from '../games/06-conteur-curieux/components/RecordingsList';
import { SkillBadge } from '../games/06-conteur-curieux/components/SkillBadge';
import { StarsRow } from '../games/06-conteur-curieux/components/StarsRow';
import { StoryCard } from '../games/06-conteur-curieux/components/StoryCard';
import { StoryIllustration } from '../games/06-conteur-curieux/components/StoryIllustration';
import { StoryReader } from '../games/06-conteur-curieux/components/StoryReader';
import { VocabularyBubble } from '../games/06-conteur-curieux/components/VocabularyBubble';
import { AnimatedButterfly } from '../components/decorations/AnimatedButterfly';
import { AnimatedCloud } from '../components/decorations/AnimatedCloud';
import { AnimatedSun } from '../components/decorations/AnimatedSun';
import { AnimatedTree } from '../components/decorations/AnimatedTree';
import { FloatingFlowers } from '../components/decorations/FloatingFlowers';
import { Hills as Hills$Decorations } from '../components/decorations/Hills';
import { Disk } from '../games/01-hanoi/components/Disk';
import { DraggableDisk } from '../games/01-hanoi/components/DraggableDisk';
import { DraggableDiskEnhanced } from '../games/01-hanoi/components/DraggableDiskEnhanced';
import { DraggableGameBoard } from '../games/01-hanoi/components/DraggableGameBoard';
import { DraggableTower } from '../games/01-hanoi/components/DraggableTower';
import { FloatingButtons } from '../games/01-hanoi/components/FloatingButtons';
import { GameBackground } from '../games/01-hanoi/components/GameBackground';
import { GameBoard } from '../games/01-hanoi/components/GameBoard';
import { HanoiIntroScreen } from '../games/01-hanoi/screens/HanoiIntroScreen';
import { HanoiVictoryScreen } from '../games/01-hanoi/screens/HanoiVictoryScreen';
import { MascotOwl } from '../games/01-hanoi/components/MascotOwl';
import { ProgressPanel } from '../games/01-hanoi/components/ProgressPanel';
import { Tower } from '../games/01-hanoi/components/Tower';
import { TowerLabel } from '../games/01-hanoi/components/TowerLabel';
import { VictoryCelebration } from '../games/01-hanoi/components/VictoryCelebration';
import { WoodenBase } from '../games/01-hanoi/components/WoodenBase';
import { CardBack } from '../games/01-hanoi/components/feedback/CardBack';
import { CardFront } from '../games/01-hanoi/components/feedback/CardFront';
import { CollectibleCardFlip } from '../games/01-hanoi/components/feedback/CollectibleCardFlip';
import { CollectionProgress } from '../games/01-hanoi/components/feedback/CollectionProgress';
import { MascotCelebration } from '../games/01-hanoi/components/feedback/MascotCelebration';
import { PopupHeader } from '../games/01-hanoi/components/feedback/PopupHeader';
import { StatsSection } from '../games/01-hanoi/components/feedback/StatsSection';
import { VictoryMascot } from '../games/01-hanoi/components/feedback/VictoryMascot';
import { VictoryOverlay } from '../games/01-hanoi/components/feedback/VictoryOverlay';
import { VictoryPopup } from '../games/01-hanoi/components/feedback/VictoryPopup';
import { ActionButton } from '../components/home-v10/GameCardComponents';
import { CategoryBadge } from '../components/home-v10/GameCardComponents';
import { CategoryFilterBar } from '../components/home-v10/CategoryFilterBar';
import { CategoryFilters } from '../components/home-v10/CategoryFilters';
import { CollectionFloating } from '../components/home-v10/CollectionFloating';
import { ForestBackgroundV10 } from '../components/home-v10/ForestBackgroundV10';
import { GameCardV10 } from '../components/home-v10/GameCardV10';
import { HomeHeaderV10 } from '../components/home-v10/HomeHeaderV10';
import { MedalBadge } from '../components/home-v10/GameCardComponents';
import { PiouFloating } from '../components/home-v10/PiouFloating';
import { ProgressBar } from '../components/home-v10/GameCardComponents';
import { Bee } from '../components/home-v10/animals/Bee';
import { Birds } from '../components/home-v10/animals/Birds';
import { Butterflies } from '../components/home-v10/animals/Butterflies';
import { Ladybug } from '../components/home-v10/animals/Ladybug';
import { Rabbit } from '../components/home-v10/animals/Rabbit';
import { Squirrel } from '../components/home-v10/animals/Squirrel';
import { AttentionIcon } from '../components/home-v10/category-icons/AttentionIcon';
import { ChiffresIcon } from '../components/home-v10/category-icons/ChiffresIcon';
import { CreativiteIcon } from '../components/home-v10/category-icons/CreativiteIcon';
import { FavorisIcon } from '../components/home-v10/category-icons/FavorisIcon';
import { FormesIcon } from '../components/home-v10/category-icons/FormesIcon';
import { LogiqueIcon } from '../components/home-v10/category-icons/LogiqueIcon';
import { MotsIcon } from '../components/home-v10/category-icons/MotsIcon';
import { TousIcon } from '../components/home-v10/category-icons/TousIcon';
import { Bushes } from '../components/home-v10/layers/Bushes';
import { Clouds } from '../components/home-v10/layers/Clouds';
import { Garden } from '../components/home-v10/layers/Garden';
import { Hills as Hills$HomeV10Layers } from '../components/home-v10/layers/Hills';
import { MountainsFar } from '../components/home-v10/layers/Mountains';
import { MountainsNear } from '../components/home-v10/layers/Mountains';
import { Sky } from '../components/home-v10/layers/Sky';
import { Sun as Sun$HomeV10Layers } from '../components/home-v10/layers/Sun';
import { Trees as Trees$HomeV10Layers } from '../components/home-v10/layers/Trees';
import { Avatar } from '../games/03-labyrinthe/components/Avatar';
import { InstructionQueue } from '../games/03-labyrinthe/components/InstructionQueue';
import { InteractiveElement } from '../games/03-labyrinthe/components/InteractiveElement';
import { Inventory } from '../games/03-labyrinthe/components/Inventory';
import { LabyrintheGame } from '../games/03-labyrinthe/LabyrintheGame';
import { LabyrintheIntroScreen } from '../games/03-labyrinthe/screens/LabyrintheIntroScreen';
import { MazeCell } from '../games/03-labyrinthe/components/MazeCell';
import { MazeGrid } from '../games/03-labyrinthe/components/MazeGrid';
import { PathTrail } from '../games/03-labyrinthe/components/PathTrail';
import { ProgrammingControls } from '../games/03-labyrinthe/components/ProgrammingControls';
import { VictoryScreen } from '../games/03-labyrinthe/components/VictoryScreen';
import { GameContainer } from '../components/layout/GameContainer';
import { AdaMascot } from '../games/09-logix-grid/components/AdaMascot';
import { CluePanel } from '../games/09-logix-grid/components/CluePanel';
import { GameBoard as GameBoard$LogixGrid } from '../games/09-logix-grid/components/GameBoard';
import { GridCell } from '../games/09-logix-grid/components/GridCell';
import { LogixGrid } from '../games/09-logix-grid/components/LogixGrid';
import { CalcMascot } from '../games/11-math-blocks/components/CalcMascot';
import { GameGrid } from '../games/11-math-blocks/components/GameGrid';
import { MathBlock } from '../games/11-math-blocks/components/MathBlock';
import { MathHanoiIntroScreen } from '../games/11-math-blocks/screens/MathHanoiIntroScreen';
import { MathPlayScreen } from '../games/11-math-blocks/screens/MathPlayScreen';
import { MathVictoryScreen } from '../games/11-math-blocks/screens/MathVictoryScreen';
import { ScoreDisplay } from '../games/11-math-blocks/components/ScoreDisplay';
import { MatricesIntroScreen } from '../games/12-matrices-magiques/screens/MatricesIntroScreen';
import { MatricesPuzzleScreen } from '../games/12-matrices-magiques/screens/MatricesPuzzleScreen';
import { MatricesVictoryScreen } from '../games/12-matrices-magiques/screens/MatricesVictoryScreen';
import { ChoiceButton } from '../games/12-matrices-magiques/components/choices/ChoiceButton';
import { ChoicePanel } from '../games/12-matrices-magiques/components/choices/ChoicePanel';
import { MatrixCell } from '../games/12-matrices-magiques/components/grid/MatrixCell';
import { MatrixGrid } from '../games/12-matrices-magiques/components/grid/MatrixGrid';
import { PixelMascot } from '../games/12-matrices-magiques/components/mascot/PixelMascot';
import { PixelWithBubble } from '../games/12-matrices-magiques/components/mascot/PixelWithBubble';
import { SpeechBubble } from '../games/12-matrices-magiques/components/mascot/SpeechBubble';
import { ShapeRenderer } from '../games/12-matrices-magiques/components/shapes/ShapeRenderer';
import { AttemptsDisplay } from '../games/12-matrices-magiques/components/ui/AttemptsDisplay';
import { ProgressDots } from '../games/12-matrices-magiques/components/ui/ProgressDots';
import { ValidateButton } from '../games/12-matrices-magiques/components/ui/ValidateButton';
import { WorldCard } from '../games/12-matrices-magiques/components/world/WorldCard';
import { WorldSelector } from '../games/12-matrices-magiques/components/world/WorldSelector';
import { GameBoard as GameBoard$Memory } from '../games/07-memory/components/GameBoard';
import { MemoryCard } from '../games/07-memory/components/MemoryCard';
import { MemoryGrid } from '../games/07-memory/components/MemoryGrid';
import { MemoryIntroScreen } from '../games/07-memory/screens/MemoryIntroScreen';
import { MemoMascot } from '../games/07-memory/components/mascot/MemoMascot';
import { ClueList } from '../games/10-mots-croises/components/ClueList';
import { CrosswordCell } from '../games/10-mots-croises/components/CrosswordCell';
import { CrosswordGrid } from '../games/10-mots-croises/components/CrosswordGrid';
import { GameBoard as GameBoard$MotsCroises } from '../games/10-mots-croises/components/GameBoard';
import { Keyboard } from '../games/10-mots-croises/components/Keyboard';
import { LexieMascot } from '../games/10-mots-croises/components/LexieMascot';
import MotsCroisesIntroScreen from '../games/10-mots-croises/screens/MotsCroisesIntroScreen';
import { HomeScreenV10 } from '../screens/HomeScreenV10';
import { ActivityTimeline } from '../components/parent/ActivityTimeline';
import { BadgesGallery } from '../components/parent/BadgesGallery';
import { BadgesSection } from '../components/parent/BadgesGallery';
import { BehaviorInsights } from '../components/parent/BehaviorInsights';
import { ChildSelector } from '../components/parent/ChildSelector';
import { GoalEditor } from '../components/parent/GoalEditor';
import { GoalsSection } from '../components/parent/GoalsSection';
import { ParentDashboard } from '../components/parent/ParentDashboard';
import { ParentDrawer } from '../components/parent/ParentDrawer';
import { ParentTabs } from '../components/parent/ParentTabs';
import { ParentZone } from '../components/parent/ParentZone';
import { ProgressChart } from '../components/parent/ProgressChart';
import { RecommendationsCard } from '../components/parent/RecommendationsCard';
import { ScreenTimeCard } from '../components/parent/ScreenTimeCard';
import { SkillsRadar } from '../components/parent/SkillsRadar';
import { SkillsRadarV2 } from '../components/parent/SkillsRadarV2';
import { StrengthsCard } from '../components/parent/StrengthsCard';
import { WeeklyChart } from '../components/parent/WeeklyChart';
import { FelixMascot } from '../games/05-sudoku/components/FelixMascot';
import { FloatingActionButtons } from '../games/05-sudoku/components/FloatingActionButtons';
import { GameTimer } from '../games/05-sudoku/components/GameTimer';
import { LibraryDecoration } from '../games/05-sudoku/components/LibraryDecoration';
import { ProgressBar as ProgressBar$Sudoku } from '../games/05-sudoku/components/ProgressBar';
import { StatsPanel } from '../games/05-sudoku/components/StatsPanel';
import { SudokuBackground } from '../games/05-sudoku/components/SudokuBackground';
import { SudokuCell } from '../games/05-sudoku/components/SudokuCell';
import { SudokuGameArea } from '../games/05-sudoku/components/SudokuGameArea';
import { SudokuGrid } from '../games/05-sudoku/components/SudokuGrid';
import { SudokuIntroScreen } from '../games/05-sudoku/screens/SudokuIntroScreen';
import { SudokuLevelCard } from '../games/05-sudoku/components/SudokuLevelCard';
import { SudokuProgressPanel } from '../games/05-sudoku/components/SudokuProgressPanel';
import { SymbolSelector } from '../games/05-sudoku/components/SymbolSelector';
import { TrainingModeSelector } from '../games/05-sudoku/components/TrainingModeSelector';
import { ChoicePanel as ChoicePanel$SuitesLogiques } from '../games/02-suites-logiques/components/ChoicePanel';
import { MascotRobot } from '../games/02-suites-logiques/components/MascotRobot';
import { MissingSlot } from '../games/02-suites-logiques/components/MissingSlot';
import { SequenceDisplay } from '../games/02-suites-logiques/components/SequenceDisplay';
import { SequenceElement } from '../games/02-suites-logiques/components/SequenceElement';
import { SuitesIntroScreen } from '../games/02-suites-logiques/screens/SuitesIntroScreen';
import { SuitesLogiquesGame } from '../games/02-suites-logiques/components/SuitesLogiquesGame';
import { AlienSVG } from '../games/02-suites-logiques/components/svg/SpaceElements';
import { ChickenSVG } from '../games/02-suites-logiques/components/svg/FarmAnimals';
import { CircleSVG } from '../games/02-suites-logiques/components/svg/GeometricShapes';
import { ClefSVG } from '../games/02-suites-logiques/components/svg/MusicElements';
import { CowSVG } from '../games/02-suites-logiques/components/svg/FarmAnimals';
import { DiamondSVG } from '../games/02-suites-logiques/components/svg/GeometricShapes';
import { DoubleNoteSVG } from '../games/02-suites-logiques/components/svg/MusicElements';
import { DrumSVG } from '../games/02-suites-logiques/components/svg/MusicElements';
import { HorseSVG } from '../games/02-suites-logiques/components/svg/FarmAnimals';
import { MoonSVG } from '../games/02-suites-logiques/components/svg/SpaceElements';
import { NoteSVG } from '../games/02-suites-logiques/components/svg/MusicElements';
import { PigSVG } from '../games/02-suites-logiques/components/svg/FarmAnimals';
import { PlanetSVG } from '../games/02-suites-logiques/components/svg/SpaceElements';
import { RocketSVG } from '../games/02-suites-logiques/components/svg/SpaceElements';
import { SheepSVG } from '../games/02-suites-logiques/components/svg/FarmAnimals';
import { SquareSVG } from '../games/02-suites-logiques/components/svg/GeometricShapes';
import { StaffNoteSVG } from '../games/02-suites-logiques/components/svg/MusicElements';
import { StarSpaceSVG } from '../games/02-suites-logiques/components/svg/SpaceElements';
import { StarSVG } from '../games/02-suites-logiques/components/svg/GeometricShapes';
import { TriangleSVG } from '../games/02-suites-logiques/components/svg/GeometricShapes';
import { ShadowShape } from '../games/08-tangram/components/ShadowShape';
import { TangramBoard } from '../games/08-tangram/components/TangramBoard';
import { TangramPiece } from '../games/08-tangram/components/TangramPiece';

// ============================================================
// TYPE DEFINITIONS
// ============================================================
export interface PlaygroundComponent {
  id: string;
  name: string;
  category: string;
  filePath?: string;
  component: React.ComponentType<any>;
  defaultProps?: Record<string, any>;
  description?: string;
}

// ============================================================
// AUTO-GENERATED REGISTRY
// ============================================================
export const COMPONENT_REGISTRY: PlaygroundComponent[] = [
  {
    id: 'assistant-assistant-bubble',
    name: 'AssistantBubble',
    category: 'Assistant',
    filePath: 'components/assistant/AssistantBubble.tsx',
    component: AssistantBubble,
    defaultProps: {},
    description: 'AssistantBubble component',
  },
  {
    id: 'background-animated-clouds',
    name: 'AnimatedClouds',
    category: 'Background',
    filePath: 'components/background/AnimatedCloud.tsx',
    component: AnimatedClouds,
    defaultProps: {},
    description: 'AnimatedClouds component',
  },
  {
    id: 'background-flowers',
    name: 'Flowers',
    category: 'Background',
    filePath: 'components/background/Flowers.tsx',
    component: Flowers,
    defaultProps: {},
    description: 'Flowers component',
  },
  {
    id: 'background-forest-background',
    name: 'ForestBackground',
    category: 'Background',
    filePath: 'components/background/ForestBackground.tsx',
    component: ForestBackground,
    defaultProps: {},
    description: 'ForestBackground component',
  },
  {
    id: 'background-hills',
    name: 'Hills',
    category: 'Background',
    filePath: 'components/background/Hills.tsx',
    component: Hills,
    defaultProps: {},
    description: 'Hills component',
  },
  {
    id: 'background-mountains',
    name: 'Mountains',
    category: 'Background',
    filePath: 'components/background/Mountains.tsx',
    component: Mountains,
    defaultProps: {},
    description: 'Mountains component',
  },
  {
    id: 'background-sun',
    name: 'Sun',
    category: 'Background',
    filePath: 'components/background/Sun.tsx',
    component: Sun,
    defaultProps: {},
    description: 'Sun component',
  },
  {
    id: 'background-trees',
    name: 'Trees',
    category: 'Background',
    filePath: 'components/background/Trees.tsx',
    component: Trees,
    defaultProps: {},
    description: 'Trees component',
  },
  {
    id: 'background-animals-dragonfly',
    name: 'Dragonfly',
    category: 'Background Animals',
    filePath: 'components/background/animals/Dragonfly.tsx',
    component: Dragonfly,
    defaultProps: {},
    description: 'Dragonfly component',
  },
  {
    id: 'balance-balance-game-screen',
    name: 'BalanceGameScreen',
    category: 'Balance',
    filePath: 'games/04-balance/screens/BalanceGameScreen.tsx',
    component: BalanceGameScreen,
    defaultProps: {},
    description: 'BalanceGameScreen component',
  },
  {
    id: 'balance-balance-hanoi-intro-screen',
    name: 'BalanceHanoiIntroScreen',
    category: 'Balance',
    filePath: 'games/04-balance/screens/BalanceHanoiIntroScreen.tsx',
    component: BalanceHanoiIntroScreen,
    defaultProps: {},
    description: 'BalanceHanoiIntroScreen component',
  },
  {
    id: 'balance-balance-intro-screen',
    name: 'BalanceIntroScreen',
    category: 'Balance',
    filePath: 'games/04-balance/screens/BalanceIntroScreen.tsx',
    component: BalanceIntroScreen,
    defaultProps: {},
    description: 'BalanceIntroScreen component',
  },
  {
    id: 'balance-balance-scale',
    name: 'BalanceScale',
    category: 'Balance',
    filePath: 'games/04-balance/components/BalanceScale.tsx',
    component: BalanceScale,
    defaultProps: {},
    description: 'BalanceScale component',
  },
  {
    id: 'balance-dr-hibou',
    name: 'DrHibou',
    category: 'Balance',
    filePath: 'games/04-balance/components/DrHibou.tsx',
    component: DrHibou,
    defaultProps: {},
    description: 'DrHibou component',
  },
  {
    id: 'balance-equivalence-journal',
    name: 'EquivalenceJournal',
    category: 'Balance',
    filePath: 'games/04-balance/components/EquivalenceJournal.tsx',
    component: EquivalenceJournal,
    defaultProps: {},
    description: 'EquivalenceJournal component',
  },
  {
    id: 'balance-level-selector',
    name: 'LevelSelector',
    category: 'Balance',
    filePath: 'games/04-balance/components/LevelSelector.tsx',
    component: LevelSelector,
    defaultProps: {},
    description: 'LevelSelector component',
  },
  {
    id: 'balance-sandbox-mode',
    name: 'SandboxMode',
    category: 'Balance',
    filePath: 'games/04-balance/components/SandboxMode.tsx',
    component: SandboxMode,
    defaultProps: {},
    description: 'SandboxMode component',
  },
  {
    id: 'balance-weight-object',
    name: 'WeightObject',
    category: 'Balance',
    filePath: 'games/04-balance/components/WeightObject.tsx',
    component: WeightObject,
    defaultProps: {},
    description: 'WeightObject component',
  },
  {
    id: 'collection-card-detail-modal',
    name: 'CardDetailModal',
    category: 'Collection',
    filePath: 'components/collection/CardDetailModal.tsx',
    component: CardDetailModal,
    defaultProps: {},
    description: 'CardDetailModal component',
  },
  {
    id: 'collection-card-unlock-screen',
    name: 'CardUnlockScreen',
    category: 'Collection',
    filePath: 'components/collection/CardUnlockScreen.tsx',
    component: CardUnlockScreen,
    defaultProps: {},
    description: 'CardUnlockScreen component',
  },
  {
    id: 'collection-category-tabs',
    name: 'CategoryTabs',
    category: 'Collection',
    filePath: 'components/collection/CategoryTabs.tsx',
    component: CategoryTabs,
    defaultProps: {},
    description: 'CategoryTabs component',
  },
  {
    id: 'collection-collection-book',
    name: 'CollectionBook',
    category: 'Collection',
    filePath: 'components/collection/CollectionBook.tsx',
    component: CollectionBook,
    defaultProps: {},
    description: 'CollectionBook component',
  },
  {
    id: 'collection-collection-card',
    name: 'CollectionCard',
    category: 'Collection',
    filePath: 'components/collection/CollectionCard.tsx',
    component: CollectionCard,
    defaultProps: {},
    description: 'CollectionCard component',
  },
  {
    id: 'collection-collection-page',
    name: 'CollectionPage',
    category: 'Collection',
    filePath: 'components/collection/CollectionPage.tsx',
    component: CollectionPage,
    defaultProps: {},
    description: 'CollectionPage component',
  },
  {
    id: 'common-back-button',
    name: 'BackButton',
    category: 'Common',
    filePath: 'components/common/BackButton.tsx',
    component: BackButton,
    defaultProps: {},
    description: 'BackButton component',
  },
  {
    id: 'common-button',
    name: 'Button',
    category: 'Common',
    filePath: 'components/common/Button.tsx',
    component: Button,
    defaultProps: {},
    description: 'Button component',
  },
  {
    id: 'common-card-flip',
    name: 'CardFlip',
    category: 'Common',
    filePath: 'components/common/CardFlip.tsx',
    component: CardFlip,
    defaultProps: {},
    description: 'CardFlip component',
  },
  {
    id: 'common-confetti',
    name: 'Confetti',
    category: 'Common',
    filePath: 'components/common/Confetti.tsx',
    component: Confetti,
    defaultProps: {},
    description: 'Confetti component',
  },
  {
    id: 'common-game-action-buttons',
    name: 'GameActionButtons',
    category: 'Common',
    filePath: 'components/common/GameActionButtons.tsx',
    component: GameActionButtons,
    defaultProps: {},
    description: 'GameActionButtons component',
  },
  {
    id: 'common-game-intro-template',
    name: 'GameIntroTemplate',
    category: 'Common',
    filePath: 'components/common/GameIntroTemplate.tsx',
    component: GameIntroTemplate,
    defaultProps: {},
    description: 'GameIntroTemplate component',
  },
  {
    id: 'common-game-modal',
    name: 'GameModal',
    category: 'Common',
    filePath: 'components/common/GameModal.tsx',
    component: GameModal,
    defaultProps: {},
    description: 'GameModal component',
  },
  {
    id: 'common-hint-button',
    name: 'HintButton',
    category: 'Common',
    filePath: 'components/common/HintButton.tsx',
    component: HintButton,
    defaultProps: {},
    description: 'HintButton component',
  },
  {
    id: 'common-icon-button',
    name: 'IconButton',
    category: 'Common',
    filePath: 'components/common/IconButton.tsx',
    component: IconButton,
    defaultProps: {},
    description: 'IconButton component',
  },
  {
    id: 'common-mascot-bubble',
    name: 'MascotBubble',
    category: 'Common',
    filePath: 'components/common/MascotBubble.tsx',
    component: MascotBubble,
    defaultProps: {},
    description: 'MascotBubble component',
  },
  {
    id: 'common-page-container',
    name: 'PageContainer',
    category: 'Common',
    filePath: 'components/common/PageContainer.tsx',
    component: PageContainer,
    defaultProps: {},
    description: 'PageContainer component',
  },
  {
    id: 'common-parent-gate',
    name: 'ParentGate',
    category: 'Common',
    filePath: 'components/common/ParentGate.tsx',
    component: ParentGate,
    defaultProps: {},
    description: 'ParentGate component',
  },
  {
    id: 'common-performance-stats',
    name: 'PerformanceStats',
    category: 'Common',
    filePath: 'components/common/PerformanceStats.tsx',
    component: PerformanceStats,
    defaultProps: {},
    description: 'PerformanceStats component',
  },
  {
    id: 'common-progress-indicator',
    name: 'ProgressIndicator',
    category: 'Common',
    filePath: 'components/common/ProgressIndicator.tsx',
    component: ProgressIndicator,
    defaultProps: {},
    description: 'ProgressIndicator component',
  },
  {
    id: 'common-screen-background',
    name: 'ScreenBackground',
    category: 'Common',
    filePath: 'components/common/ScreenBackground.tsx',
    component: ScreenBackground,
    defaultProps: {},
    description: 'ScreenBackground component',
  },
  {
    id: 'common-screen-header',
    name: 'ScreenHeader',
    category: 'Common',
    filePath: 'components/common/ScreenHeader.tsx',
    component: ScreenHeader,
    defaultProps: {},
    description: 'ScreenHeader component',
  },
  {
    id: 'common-victory-card',
    name: 'VictoryCard',
    category: 'Common',
    filePath: 'components/common/VictoryCard.tsx',
    component: VictoryCard,
    defaultProps: {},
    description: 'VictoryCard component',
  },
  {
    id: 'common-victory-overlay-base',
    name: 'VictoryOverlayBase',
    category: 'Common',
    filePath: 'components/common/VictoryOverlayBase.tsx',
    component: VictoryOverlayBase,
    defaultProps: {},
    description: 'VictoryOverlayBase component',
  },
  {
    id: 'conteur-curieux-adventure-scene',
    name: 'AdventureScene',
    category: 'Conteur Curieux',
    filePath: 'games/06-conteur-curieux/assets/illustrations/AdventureScene.tsx',
    component: AdventureScene,
    defaultProps: {},
    description: 'AdventureScene component',
  },
  {
    id: 'conteur-curieux-answer-button',
    name: 'AnswerButton',
    category: 'Conteur Curieux',
    filePath: 'games/06-conteur-curieux/components/AnswerButton.tsx',
    component: AnswerButton,
    defaultProps: {},
    description: 'AnswerButton component',
  },
  {
    id: 'conteur-curieux-audio-player',
    name: 'AudioPlayer',
    category: 'Conteur Curieux',
    filePath: 'games/06-conteur-curieux/components/AudioPlayer.tsx',
    component: AudioPlayer,
    defaultProps: {},
    description: 'AudioPlayer component',
  },
  {
    id: 'conteur-curieux-collectible-card',
    name: 'CollectibleCard',
    category: 'Conteur Curieux',
    filePath: 'games/06-conteur-curieux/components/CollectibleCard.tsx',
    component: CollectibleCard,
    defaultProps: {},
    description: 'CollectibleCard component',
  },
  {
    id: 'conteur-curieux-conteur-intro-screen',
    name: 'ConteurIntroScreen',
    category: 'Conteur Curieux',
    filePath: 'games/06-conteur-curieux/screens/ConteurIntroScreen.tsx',
    component: ConteurIntroScreen,
    defaultProps: {},
    description: 'ConteurIntroScreen component',
  },
  {
    id: 'conteur-curieux-conteur-parent-screen',
    name: 'ConteurParentScreen',
    category: 'Conteur Curieux',
    filePath: 'games/06-conteur-curieux/screens/ConteurParentScreen.tsx',
    component: ConteurParentScreen,
    defaultProps: {},
    description: 'ConteurParentScreen component',
  },
  {
    id: 'conteur-curieux-conteur-questions-screen',
    name: 'ConteurQuestionsScreen',
    category: 'Conteur Curieux',
    filePath: 'games/06-conteur-curieux/screens/ConteurQuestionsScreen.tsx',
    component: ConteurQuestionsScreen,
    defaultProps: {},
    description: 'ConteurQuestionsScreen component',
  },
  {
    id: 'conteur-curieux-conteur-recording-screen',
    name: 'ConteurRecordingScreen',
    category: 'Conteur Curieux',
    filePath: 'games/06-conteur-curieux/screens/ConteurRecordingScreen.tsx',
    component: ConteurRecordingScreen,
    defaultProps: {},
    description: 'ConteurRecordingScreen component',
  },
  {
    id: 'conteur-curieux-conteur-story-screen',
    name: 'ConteurStoryScreen',
    category: 'Conteur Curieux',
    filePath: 'games/06-conteur-curieux/screens/ConteurStoryScreen.tsx',
    component: ConteurStoryScreen,
    defaultProps: {},
    description: 'ConteurStoryScreen component',
  },
  {
    id: 'conteur-curieux-conteur-victory-screen',
    name: 'ConteurVictoryScreen',
    category: 'Conteur Curieux',
    filePath: 'games/06-conteur-curieux/screens/ConteurVictoryScreen.tsx',
    component: ConteurVictoryScreen,
    defaultProps: {},
    description: 'ConteurVictoryScreen component',
  },
  {
    id: 'conteur-curieux-family-scene',
    name: 'FamilyScene',
    category: 'Conteur Curieux',
    filePath: 'games/06-conteur-curieux/assets/illustrations/FamilyScene.tsx',
    component: FamilyScene,
    defaultProps: {},
    description: 'FamilyScene component',
  },
  {
    id: 'conteur-curieux-feedback-overlay',
    name: 'FeedbackOverlay',
    category: 'Conteur Curieux',
    filePath: 'games/06-conteur-curieux/components/FeedbackOverlay.tsx',
    component: FeedbackOverlay,
    defaultProps: {},
    description: 'FeedbackOverlay component',
  },
  {
    id: 'conteur-curieux-filter-tabs',
    name: 'FilterTabs',
    category: 'Conteur Curieux',
    filePath: 'games/06-conteur-curieux/components/FilterTabs.tsx',
    component: FilterTabs,
    defaultProps: {},
    description: 'FilterTabs component',
  },
  {
    id: 'conteur-curieux-forest-scene',
    name: 'ForestScene',
    category: 'Conteur Curieux',
    filePath: 'games/06-conteur-curieux/assets/illustrations/ForestScene.tsx',
    component: ForestScene,
    defaultProps: {},
    description: 'ForestScene component',
  },
  {
    id: 'conteur-curieux-friendship-scene',
    name: 'FriendshipScene',
    category: 'Conteur Curieux',
    filePath: 'games/06-conteur-curieux/assets/illustrations/FriendshipScene.tsx',
    component: FriendshipScene,
    defaultProps: {},
    description: 'FriendshipScene component',
  },
  {
    id: 'conteur-curieux-library-background',
    name: 'LibraryBackground',
    category: 'Conteur Curieux',
    filePath: 'games/06-conteur-curieux/components/LibraryBackground.tsx',
    component: LibraryBackground,
    defaultProps: {},
    description: 'LibraryBackground component',
  },
  {
    id: 'conteur-curieux-magic-scene',
    name: 'MagicScene',
    category: 'Conteur Curieux',
    filePath: 'games/06-conteur-curieux/assets/illustrations/MagicScene.tsx',
    component: MagicScene,
    defaultProps: {},
    description: 'MagicScene component',
  },
  {
    id: 'conteur-curieux-mode-selection-modal',
    name: 'ModeSelectionModal',
    category: 'Conteur Curieux',
    filePath: 'games/06-conteur-curieux/components/ModeSelectionModal.tsx',
    component: ModeSelectionModal,
    defaultProps: {},
    description: 'ModeSelectionModal component',
  },
  {
    id: 'conteur-curieux-plume-mascot',
    name: 'PlumeMascot',
    category: 'Conteur Curieux',
    filePath: 'games/06-conteur-curieux/components/PlumeMascot.tsx',
    component: PlumeMascot,
    defaultProps: {},
    description: 'PlumeMascot component',
  },
  {
    id: 'conteur-curieux-question-card',
    name: 'QuestionCard',
    category: 'Conteur Curieux',
    filePath: 'games/06-conteur-curieux/components/QuestionCard.tsx',
    component: QuestionCard,
    defaultProps: {},
    description: 'QuestionCard component',
  },
  {
    id: 'conteur-curieux-radar-chart',
    name: 'RadarChart',
    category: 'Conteur Curieux',
    filePath: 'games/06-conteur-curieux/components/RadarChart.tsx',
    component: RadarChart,
    defaultProps: {},
    description: 'RadarChart component',
  },
  {
    id: 'conteur-curieux-rays-effect',
    name: 'RaysEffect',
    category: 'Conteur Curieux',
    filePath: 'games/06-conteur-curieux/components/RaysEffect.tsx',
    component: RaysEffect,
    defaultProps: {},
    description: 'RaysEffect component',
  },
  {
    id: 'conteur-curieux-recordings-list',
    name: 'RecordingsList',
    category: 'Conteur Curieux',
    filePath: 'games/06-conteur-curieux/components/RecordingsList.tsx',
    component: RecordingsList,
    defaultProps: {},
    description: 'RecordingsList component',
  },
  {
    id: 'conteur-curieux-skill-badge',
    name: 'SkillBadge',
    category: 'Conteur Curieux',
    filePath: 'games/06-conteur-curieux/components/SkillBadge.tsx',
    component: SkillBadge,
    defaultProps: {},
    description: 'SkillBadge component',
  },
  {
    id: 'conteur-curieux-stars-row',
    name: 'StarsRow',
    category: 'Conteur Curieux',
    filePath: 'games/06-conteur-curieux/components/StarsRow.tsx',
    component: StarsRow,
    defaultProps: {},
    description: 'StarsRow component',
  },
  {
    id: 'conteur-curieux-story-card',
    name: 'StoryCard',
    category: 'Conteur Curieux',
    filePath: 'games/06-conteur-curieux/components/StoryCard.tsx',
    component: StoryCard,
    defaultProps: {},
    description: 'StoryCard component',
  },
  {
    id: 'conteur-curieux-story-illustration',
    name: 'StoryIllustration',
    category: 'Conteur Curieux',
    filePath: 'games/06-conteur-curieux/components/StoryIllustration.tsx',
    component: StoryIllustration,
    defaultProps: {},
    description: 'StoryIllustration component',
  },
  {
    id: 'conteur-curieux-story-reader',
    name: 'StoryReader',
    category: 'Conteur Curieux',
    filePath: 'games/06-conteur-curieux/components/StoryReader.tsx',
    component: StoryReader,
    defaultProps: {},
    description: 'StoryReader component',
  },
  {
    id: 'conteur-curieux-vocabulary-bubble',
    name: 'VocabularyBubble',
    category: 'Conteur Curieux',
    filePath: 'games/06-conteur-curieux/components/VocabularyBubble.tsx',
    component: VocabularyBubble,
    defaultProps: {},
    description: 'VocabularyBubble component',
  },
  {
    id: 'decorations-animated-butterfly',
    name: 'AnimatedButterfly',
    category: 'Decorations',
    filePath: 'components/decorations/AnimatedButterfly.tsx',
    component: AnimatedButterfly,
    defaultProps: {},
    description: 'AnimatedButterfly component',
  },
  {
    id: 'decorations-animated-cloud',
    name: 'AnimatedCloud',
    category: 'Decorations',
    filePath: 'components/decorations/AnimatedCloud.tsx',
    component: AnimatedCloud,
    defaultProps: {},
    description: 'AnimatedCloud component',
  },
  {
    id: 'decorations-animated-sun',
    name: 'AnimatedSun',
    category: 'Decorations',
    filePath: 'components/decorations/AnimatedSun.tsx',
    component: AnimatedSun,
    defaultProps: {},
    description: 'AnimatedSun component',
  },
  {
    id: 'decorations-animated-tree',
    name: 'AnimatedTree',
    category: 'Decorations',
    filePath: 'components/decorations/AnimatedTree.tsx',
    component: AnimatedTree,
    defaultProps: {},
    description: 'AnimatedTree component',
  },
  {
    id: 'decorations-floating-flowers',
    name: 'FloatingFlowers',
    category: 'Decorations',
    filePath: 'components/decorations/FloatingFlowers.tsx',
    component: FloatingFlowers,
    defaultProps: {},
    description: 'FloatingFlowers component',
  },
  {
    id: 'decorations-hills',
    name: 'Hills',
    category: 'Decorations',
    filePath: 'components/decorations/Hills.tsx',
    component: Hills$Decorations,
    defaultProps: {},
    description: 'Hills component',
  },
  {
    id: 'hanoi-disk',
    name: 'Disk',
    category: 'Hanoi',
    filePath: 'games/01-hanoi/components/Disk.tsx',
    component: Disk,
    defaultProps: {},
    description: 'Disk component',
  },
  {
    id: 'hanoi-draggable-disk',
    name: 'DraggableDisk',
    category: 'Hanoi',
    filePath: 'games/01-hanoi/components/DraggableDisk.tsx',
    component: DraggableDisk,
    defaultProps: {},
    description: 'DraggableDisk component',
  },
  {
    id: 'hanoi-draggable-disk-enhanced',
    name: 'DraggableDiskEnhanced',
    category: 'Hanoi',
    filePath: 'games/01-hanoi/components/DraggableDiskEnhanced.tsx',
    component: DraggableDiskEnhanced,
    defaultProps: {},
    description: 'DraggableDiskEnhanced component',
  },
  {
    id: 'hanoi-draggable-game-board',
    name: 'DraggableGameBoard',
    category: 'Hanoi',
    filePath: 'games/01-hanoi/components/DraggableGameBoard.tsx',
    component: DraggableGameBoard,
    defaultProps: {},
    description: 'DraggableGameBoard component',
  },
  {
    id: 'hanoi-draggable-tower',
    name: 'DraggableTower',
    category: 'Hanoi',
    filePath: 'games/01-hanoi/components/DraggableTower.tsx',
    component: DraggableTower,
    defaultProps: {},
    description: 'DraggableTower component',
  },
  {
    id: 'hanoi-floating-buttons',
    name: 'FloatingButtons',
    category: 'Hanoi',
    filePath: 'games/01-hanoi/components/FloatingButtons.tsx',
    component: FloatingButtons,
    defaultProps: {},
    description: 'FloatingButtons component',
  },
  {
    id: 'hanoi-game-background',
    name: 'GameBackground',
    category: 'Hanoi',
    filePath: 'games/01-hanoi/components/GameBackground.tsx',
    component: GameBackground,
    defaultProps: {},
    description: 'GameBackground component',
  },
  {
    id: 'hanoi-game-board',
    name: 'GameBoard',
    category: 'Hanoi',
    filePath: 'games/01-hanoi/components/GameBoard.tsx',
    component: GameBoard,
    defaultProps: {},
    description: 'GameBoard component',
  },
  {
    id: 'hanoi-hanoi-intro-screen',
    name: 'HanoiIntroScreen',
    category: 'Hanoi',
    filePath: 'games/01-hanoi/screens/HanoiIntroScreen.tsx',
    component: HanoiIntroScreen,
    defaultProps: {},
    description: 'HanoiIntroScreen component',
  },
  {
    id: 'hanoi-hanoi-victory-screen',
    name: 'HanoiVictoryScreen',
    category: 'Hanoi',
    filePath: 'games/01-hanoi/screens/HanoiVictoryScreen.tsx',
    component: HanoiVictoryScreen,
    defaultProps: {},
    description: 'HanoiVictoryScreen component',
  },
  {
    id: 'hanoi-mascot-owl',
    name: 'MascotOwl',
    category: 'Hanoi',
    filePath: 'games/01-hanoi/components/MascotOwl.tsx',
    component: MascotOwl,
    defaultProps: {},
    description: 'MascotOwl component',
  },
  {
    id: 'hanoi-progress-panel',
    name: 'ProgressPanel',
    category: 'Hanoi',
    filePath: 'games/01-hanoi/components/ProgressPanel.tsx',
    component: ProgressPanel,
    defaultProps: {},
    description: 'ProgressPanel component',
  },
  {
    id: 'hanoi-tower',
    name: 'Tower',
    category: 'Hanoi',
    filePath: 'games/01-hanoi/components/Tower.tsx',
    component: Tower,
    defaultProps: {},
    description: 'Tower component',
  },
  {
    id: 'hanoi-tower-label',
    name: 'TowerLabel',
    category: 'Hanoi',
    filePath: 'games/01-hanoi/components/TowerLabel.tsx',
    component: TowerLabel,
    defaultProps: {},
    description: 'TowerLabel component',
  },
  {
    id: 'hanoi-victory-celebration',
    name: 'VictoryCelebration',
    category: 'Hanoi',
    filePath: 'games/01-hanoi/components/VictoryCelebration.tsx',
    component: VictoryCelebration,
    defaultProps: {},
    description: 'VictoryCelebration component',
  },
  {
    id: 'hanoi-wooden-base',
    name: 'WoodenBase',
    category: 'Hanoi',
    filePath: 'games/01-hanoi/components/WoodenBase.tsx',
    component: WoodenBase,
    defaultProps: {},
    description: 'WoodenBase component',
  },
  {
    id: 'hanoi---feedback-card-back',
    name: 'CardBack',
    category: 'Hanoi - Feedback',
    filePath: 'games/01-hanoi/components/feedback/CardBack.tsx',
    component: CardBack,
    defaultProps: {},
    description: 'CardBack component',
  },
  {
    id: 'hanoi---feedback-card-front',
    name: 'CardFront',
    category: 'Hanoi - Feedback',
    filePath: 'games/01-hanoi/components/feedback/CardFront.tsx',
    component: CardFront,
    defaultProps: {},
    description: 'CardFront component',
  },
  {
    id: 'hanoi---feedback-collectible-card-flip',
    name: 'CollectibleCardFlip',
    category: 'Hanoi - Feedback',
    filePath: 'games/01-hanoi/components/feedback/CollectibleCardFlip.tsx',
    component: CollectibleCardFlip,
    defaultProps: {},
    description: 'CollectibleCardFlip component',
  },
  {
    id: 'hanoi---feedback-collection-progress',
    name: 'CollectionProgress',
    category: 'Hanoi - Feedback',
    filePath: 'games/01-hanoi/components/feedback/CollectionProgress.tsx',
    component: CollectionProgress,
    defaultProps: {},
    description: 'CollectionProgress component',
  },
  {
    id: 'hanoi---feedback-mascot-celebration',
    name: 'MascotCelebration',
    category: 'Hanoi - Feedback',
    filePath: 'games/01-hanoi/components/feedback/MascotCelebration.tsx',
    component: MascotCelebration,
    defaultProps: {},
    description: 'MascotCelebration component',
  },
  {
    id: 'hanoi---feedback-popup-header',
    name: 'PopupHeader',
    category: 'Hanoi - Feedback',
    filePath: 'games/01-hanoi/components/feedback/PopupHeader.tsx',
    component: PopupHeader,
    defaultProps: {},
    description: 'PopupHeader component',
  },
  {
    id: 'hanoi---feedback-stats-section',
    name: 'StatsSection',
    category: 'Hanoi - Feedback',
    filePath: 'games/01-hanoi/components/feedback/StatsSection.tsx',
    component: StatsSection,
    defaultProps: {},
    description: 'StatsSection component',
  },
  {
    id: 'hanoi---feedback-victory-mascot',
    name: 'VictoryMascot',
    category: 'Hanoi - Feedback',
    filePath: 'games/01-hanoi/components/feedback/VictoryMascot.tsx',
    component: VictoryMascot,
    defaultProps: {},
    description: 'VictoryMascot component',
  },
  {
    id: 'hanoi---feedback-victory-overlay',
    name: 'VictoryOverlay',
    category: 'Hanoi - Feedback',
    filePath: 'games/01-hanoi/components/feedback/VictoryOverlay.tsx',
    component: VictoryOverlay,
    defaultProps: {},
    description: 'VictoryOverlay component',
  },
  {
    id: 'hanoi---feedback-victory-popup',
    name: 'VictoryPopup',
    category: 'Hanoi - Feedback',
    filePath: 'games/01-hanoi/components/feedback/VictoryPopup.tsx',
    component: VictoryPopup,
    defaultProps: {},
    description: 'VictoryPopup component',
  },
  {
    id: 'home-v10-action-button',
    name: 'ActionButton',
    category: 'Home V10',
    filePath: 'components/home-v10/GameCardComponents.tsx',
    component: ActionButton,
    defaultProps: {},
    description: 'ActionButton component',
  },
  {
    id: 'home-v10-category-badge',
    name: 'CategoryBadge',
    category: 'Home V10',
    filePath: 'components/home-v10/GameCardComponents.tsx',
    component: CategoryBadge,
    defaultProps: {},
    description: 'CategoryBadge component',
  },
  {
    id: 'home-v10-category-filter-bar',
    name: 'CategoryFilterBar',
    category: 'Home V10',
    filePath: 'components/home-v10/CategoryFilterBar.tsx',
    component: CategoryFilterBar,
    defaultProps: {},
    description: 'CategoryFilterBar component',
  },
  {
    id: 'home-v10-category-filters',
    name: 'CategoryFilters',
    category: 'Home V10',
    filePath: 'components/home-v10/CategoryFilters.tsx',
    component: CategoryFilters,
    defaultProps: {},
    description: 'CategoryFilters component',
  },
  {
    id: 'home-v10-collection-floating',
    name: 'CollectionFloating',
    category: 'Home V10',
    filePath: 'components/home-v10/CollectionFloating.tsx',
    component: CollectionFloating,
    defaultProps: {},
    description: 'CollectionFloating component',
  },
  {
    id: 'home-v10-forest-background-v10',
    name: 'ForestBackgroundV10',
    category: 'Home V10',
    filePath: 'components/home-v10/ForestBackgroundV10.tsx',
    component: ForestBackgroundV10,
    defaultProps: {},
    description: 'ForestBackgroundV10 component',
  },
  {
    id: 'home-v10-game-card-v10',
    name: 'GameCardV10',
    category: 'Home V10',
    filePath: 'components/home-v10/GameCardV10.tsx',
    component: GameCardV10,
    defaultProps: {},
    description: 'GameCardV10 component',
  },
  {
    id: 'home-v10-home-header-v10',
    name: 'HomeHeaderV10',
    category: 'Home V10',
    filePath: 'components/home-v10/HomeHeaderV10.tsx',
    component: HomeHeaderV10,
    defaultProps: {},
    description: 'HomeHeaderV10 component',
  },
  {
    id: 'home-v10-medal-badge',
    name: 'MedalBadge',
    category: 'Home V10',
    filePath: 'components/home-v10/GameCardComponents.tsx',
    component: MedalBadge,
    defaultProps: {},
    description: 'MedalBadge component',
  },
  {
    id: 'home-v10-piou-floating',
    name: 'PiouFloating',
    category: 'Home V10',
    filePath: 'components/home-v10/PiouFloating.tsx',
    component: PiouFloating,
    defaultProps: {},
    description: 'PiouFloating component',
  },
  {
    id: 'home-v10-progress-bar',
    name: 'ProgressBar',
    category: 'Home V10',
    filePath: 'components/home-v10/GameCardComponents.tsx',
    component: ProgressBar,
    defaultProps: {},
    description: 'ProgressBar component',
  },
  {
    id: 'home-v10-animals-bee',
    name: 'Bee',
    category: 'Home V10 Animals',
    filePath: 'components/home-v10/animals/Bee.tsx',
    component: Bee,
    defaultProps: {},
    description: 'Bee component',
  },
  {
    id: 'home-v10-animals-birds',
    name: 'Birds',
    category: 'Home V10 Animals',
    filePath: 'components/home-v10/animals/Birds.tsx',
    component: Birds,
    defaultProps: {},
    description: 'Birds component',
  },
  {
    id: 'home-v10-animals-butterflies',
    name: 'Butterflies',
    category: 'Home V10 Animals',
    filePath: 'components/home-v10/animals/Butterflies.tsx',
    component: Butterflies,
    defaultProps: {},
    description: 'Butterflies component',
  },
  {
    id: 'home-v10-animals-ladybug',
    name: 'Ladybug',
    category: 'Home V10 Animals',
    filePath: 'components/home-v10/animals/Ladybug.tsx',
    component: Ladybug,
    defaultProps: {},
    description: 'Ladybug component',
  },
  {
    id: 'home-v10-animals-rabbit',
    name: 'Rabbit',
    category: 'Home V10 Animals',
    filePath: 'components/home-v10/animals/Rabbit.tsx',
    component: Rabbit,
    defaultProps: {},
    description: 'Rabbit component',
  },
  {
    id: 'home-v10-animals-squirrel',
    name: 'Squirrel',
    category: 'Home V10 Animals',
    filePath: 'components/home-v10/animals/Squirrel.tsx',
    component: Squirrel,
    defaultProps: {},
    description: 'Squirrel component',
  },
  {
    id: 'home-v10-category-icons-attention-icon',
    name: 'AttentionIcon',
    category: 'Home V10 Category Icons',
    filePath: 'components/home-v10/category-icons/AttentionIcon.tsx',
    component: AttentionIcon,
    defaultProps: {},
    description: 'AttentionIcon component',
  },
  {
    id: 'home-v10-category-icons-chiffres-icon',
    name: 'ChiffresIcon',
    category: 'Home V10 Category Icons',
    filePath: 'components/home-v10/category-icons/ChiffresIcon.tsx',
    component: ChiffresIcon,
    defaultProps: {},
    description: 'ChiffresIcon component',
  },
  {
    id: 'home-v10-category-icons-creativite-icon',
    name: 'CreativiteIcon',
    category: 'Home V10 Category Icons',
    filePath: 'components/home-v10/category-icons/CreativiteIcon.tsx',
    component: CreativiteIcon,
    defaultProps: {},
    description: 'CreativiteIcon component',
  },
  {
    id: 'home-v10-category-icons-favoris-icon',
    name: 'FavorisIcon',
    category: 'Home V10 Category Icons',
    filePath: 'components/home-v10/category-icons/FavorisIcon.tsx',
    component: FavorisIcon,
    defaultProps: {},
    description: 'FavorisIcon component',
  },
  {
    id: 'home-v10-category-icons-formes-icon',
    name: 'FormesIcon',
    category: 'Home V10 Category Icons',
    filePath: 'components/home-v10/category-icons/FormesIcon.tsx',
    component: FormesIcon,
    defaultProps: {},
    description: 'FormesIcon component',
  },
  {
    id: 'home-v10-category-icons-logique-icon',
    name: 'LogiqueIcon',
    category: 'Home V10 Category Icons',
    filePath: 'components/home-v10/category-icons/LogiqueIcon.tsx',
    component: LogiqueIcon,
    defaultProps: {},
    description: 'LogiqueIcon component',
  },
  {
    id: 'home-v10-category-icons-mots-icon',
    name: 'MotsIcon',
    category: 'Home V10 Category Icons',
    filePath: 'components/home-v10/category-icons/MotsIcon.tsx',
    component: MotsIcon,
    defaultProps: {},
    description: 'MotsIcon component',
  },
  {
    id: 'home-v10-category-icons-tous-icon',
    name: 'TousIcon',
    category: 'Home V10 Category Icons',
    filePath: 'components/home-v10/category-icons/TousIcon.tsx',
    component: TousIcon,
    defaultProps: {},
    description: 'TousIcon component',
  },
  {
    id: 'home-v10-layers-bushes',
    name: 'Bushes',
    category: 'Home V10 Layers',
    filePath: 'components/home-v10/layers/Bushes.tsx',
    component: Bushes,
    defaultProps: {},
    description: 'Bushes component',
  },
  {
    id: 'home-v10-layers-clouds',
    name: 'Clouds',
    category: 'Home V10 Layers',
    filePath: 'components/home-v10/layers/Clouds.tsx',
    component: Clouds,
    defaultProps: {},
    description: 'Clouds component',
  },
  {
    id: 'home-v10-layers-garden',
    name: 'Garden',
    category: 'Home V10 Layers',
    filePath: 'components/home-v10/layers/Garden.tsx',
    component: Garden,
    defaultProps: {},
    description: 'Garden component',
  },
  {
    id: 'home-v10-layers-hills',
    name: 'Hills',
    category: 'Home V10 Layers',
    filePath: 'components/home-v10/layers/Hills.tsx',
    component: Hills$HomeV10Layers,
    defaultProps: {},
    description: 'Hills component',
  },
  {
    id: 'home-v10-layers-mountains-far',
    name: 'MountainsFar',
    category: 'Home V10 Layers',
    filePath: 'components/home-v10/layers/Mountains.tsx',
    component: MountainsFar,
    defaultProps: {},
    description: 'MountainsFar component',
  },
  {
    id: 'home-v10-layers-mountains-near',
    name: 'MountainsNear',
    category: 'Home V10 Layers',
    filePath: 'components/home-v10/layers/Mountains.tsx',
    component: MountainsNear,
    defaultProps: {},
    description: 'MountainsNear component',
  },
  {
    id: 'home-v10-layers-sky',
    name: 'Sky',
    category: 'Home V10 Layers',
    filePath: 'components/home-v10/layers/Sky.tsx',
    component: Sky,
    defaultProps: {},
    description: 'Sky component',
  },
  {
    id: 'home-v10-layers-sun',
    name: 'Sun',
    category: 'Home V10 Layers',
    filePath: 'components/home-v10/layers/Sun.tsx',
    component: Sun$HomeV10Layers,
    defaultProps: {},
    description: 'Sun component',
  },
  {
    id: 'home-v10-layers-trees',
    name: 'Trees',
    category: 'Home V10 Layers',
    filePath: 'components/home-v10/layers/Trees.tsx',
    component: Trees$HomeV10Layers,
    defaultProps: {},
    description: 'Trees component',
  },
  {
    id: 'labyrinthe-avatar',
    name: 'Avatar',
    category: 'Labyrinthe',
    filePath: 'games/03-labyrinthe/components/Avatar.tsx',
    component: Avatar,
    defaultProps: {},
    description: 'Avatar component',
  },
  {
    id: 'labyrinthe-instruction-queue',
    name: 'InstructionQueue',
    category: 'Labyrinthe',
    filePath: 'games/03-labyrinthe/components/InstructionQueue.tsx',
    component: InstructionQueue,
    defaultProps: {},
    description: 'InstructionQueue component',
  },
  {
    id: 'labyrinthe-interactive-element',
    name: 'InteractiveElement',
    category: 'Labyrinthe',
    filePath: 'games/03-labyrinthe/components/InteractiveElement.tsx',
    component: InteractiveElement,
    defaultProps: {},
    description: 'InteractiveElement component',
  },
  {
    id: 'labyrinthe-inventory',
    name: 'Inventory',
    category: 'Labyrinthe',
    filePath: 'games/03-labyrinthe/components/Inventory.tsx',
    component: Inventory,
    defaultProps: {},
    description: 'Inventory component',
  },
  {
    id: 'labyrinthe-labyrinthe-game',
    name: 'LabyrintheGame',
    category: 'Labyrinthe',
    filePath: 'games/03-labyrinthe/LabyrintheGame.tsx',
    component: LabyrintheGame,
    defaultProps: {},
    description: 'LabyrintheGame component',
  },
  {
    id: 'labyrinthe-labyrinthe-intro-screen',
    name: 'LabyrintheIntroScreen',
    category: 'Labyrinthe',
    filePath: 'games/03-labyrinthe/screens/LabyrintheIntroScreen.tsx',
    component: LabyrintheIntroScreen,
    defaultProps: {},
    description: 'LabyrintheIntroScreen component',
  },
  {
    id: 'labyrinthe-maze-cell',
    name: 'MazeCell',
    category: 'Labyrinthe',
    filePath: 'games/03-labyrinthe/components/MazeCell.tsx',
    component: MazeCell,
    defaultProps: {},
    description: 'MazeCell component',
  },
  {
    id: 'labyrinthe-maze-grid',
    name: 'MazeGrid',
    category: 'Labyrinthe',
    filePath: 'games/03-labyrinthe/components/MazeGrid.tsx',
    component: MazeGrid,
    defaultProps: {},
    description: 'MazeGrid component',
  },
  {
    id: 'labyrinthe-path-trail',
    name: 'PathTrail',
    category: 'Labyrinthe',
    filePath: 'games/03-labyrinthe/components/PathTrail.tsx',
    component: PathTrail,
    defaultProps: {},
    description: 'PathTrail component',
  },
  {
    id: 'labyrinthe-programming-controls',
    name: 'ProgrammingControls',
    category: 'Labyrinthe',
    filePath: 'games/03-labyrinthe/components/ProgrammingControls.tsx',
    component: ProgrammingControls,
    defaultProps: {},
    description: 'ProgrammingControls component',
  },
  {
    id: 'labyrinthe-victory-screen',
    name: 'VictoryScreen',
    category: 'Labyrinthe',
    filePath: 'games/03-labyrinthe/components/VictoryScreen.tsx',
    component: VictoryScreen,
    defaultProps: {},
    description: 'VictoryScreen component',
  },
  {
    id: 'layout-game-container',
    name: 'GameContainer',
    category: 'Layout',
    filePath: 'components/layout/GameContainer.tsx',
    component: GameContainer,
    defaultProps: {},
    description: 'GameContainer component',
  },
  {
    id: 'logix-grid-ada-mascot',
    name: 'AdaMascot',
    category: 'Logix Grid',
    filePath: 'games/09-logix-grid/components/AdaMascot.tsx',
    component: AdaMascot,
    defaultProps: {},
    description: 'AdaMascot component',
  },
  {
    id: 'logix-grid-clue-panel',
    name: 'CluePanel',
    category: 'Logix Grid',
    filePath: 'games/09-logix-grid/components/CluePanel.tsx',
    component: CluePanel,
    defaultProps: {},
    description: 'CluePanel component',
  },
  {
    id: 'logix-grid-game-board',
    name: 'GameBoard',
    category: 'Logix Grid',
    filePath: 'games/09-logix-grid/components/GameBoard.tsx',
    component: GameBoard$LogixGrid,
    defaultProps: {},
    description: 'GameBoard component',
  },
  {
    id: 'logix-grid-grid-cell',
    name: 'GridCell',
    category: 'Logix Grid',
    filePath: 'games/09-logix-grid/components/GridCell.tsx',
    component: GridCell,
    defaultProps: {},
    description: 'GridCell component',
  },
  {
    id: 'logix-grid-logix-grid',
    name: 'LogixGrid',
    category: 'Logix Grid',
    filePath: 'games/09-logix-grid/components/LogixGrid.tsx',
    component: LogixGrid,
    defaultProps: {},
    description: 'LogixGrid component',
  },
  {
    id: 'math-blocks-calc-mascot',
    name: 'CalcMascot',
    category: 'Math Blocks',
    filePath: 'games/11-math-blocks/components/CalcMascot.tsx',
    component: CalcMascot,
    defaultProps: {},
    description: 'CalcMascot component',
  },
  {
    id: 'math-blocks-game-grid',
    name: 'GameGrid',
    category: 'Math Blocks',
    filePath: 'games/11-math-blocks/components/GameGrid.tsx',
    component: GameGrid,
    defaultProps: {},
    description: 'GameGrid component',
  },
  {
    id: 'math-blocks-math-block',
    name: 'MathBlock',
    category: 'Math Blocks',
    filePath: 'games/11-math-blocks/components/MathBlock.tsx',
    component: MathBlock,
    defaultProps: {},
    description: 'MathBlock component',
  },
  {
    id: 'math-blocks-math-hanoi-intro-screen',
    name: 'MathHanoiIntroScreen',
    category: 'Math Blocks',
    filePath: 'games/11-math-blocks/screens/MathHanoiIntroScreen.tsx',
    component: MathHanoiIntroScreen,
    defaultProps: {},
    description: 'MathHanoiIntroScreen component',
  },
  {
    id: 'math-blocks-math-play-screen',
    name: 'MathPlayScreen',
    category: 'Math Blocks',
    filePath: 'games/11-math-blocks/screens/MathPlayScreen.tsx',
    component: MathPlayScreen,
    defaultProps: {},
    description: 'MathPlayScreen component',
  },
  {
    id: 'math-blocks-math-victory-screen',
    name: 'MathVictoryScreen',
    category: 'Math Blocks',
    filePath: 'games/11-math-blocks/screens/MathVictoryScreen.tsx',
    component: MathVictoryScreen,
    defaultProps: {},
    description: 'MathVictoryScreen component',
  },
  {
    id: 'math-blocks-score-display',
    name: 'ScoreDisplay',
    category: 'Math Blocks',
    filePath: 'games/11-math-blocks/components/ScoreDisplay.tsx',
    component: ScoreDisplay,
    defaultProps: {},
    description: 'ScoreDisplay component',
  },
  {
    id: 'matrices-magiques-matrices-intro-screen',
    name: 'MatricesIntroScreen',
    category: 'Matrices Magiques',
    filePath: 'games/12-matrices-magiques/screens/MatricesIntroScreen.tsx',
    component: MatricesIntroScreen,
    defaultProps: {},
    description: 'MatricesIntroScreen component',
  },
  {
    id: 'matrices-magiques-matrices-puzzle-screen',
    name: 'MatricesPuzzleScreen',
    category: 'Matrices Magiques',
    filePath: 'games/12-matrices-magiques/screens/MatricesPuzzleScreen.tsx',
    component: MatricesPuzzleScreen,
    defaultProps: {},
    description: 'MatricesPuzzleScreen component',
  },
  {
    id: 'matrices-magiques-matrices-victory-screen',
    name: 'MatricesVictoryScreen',
    category: 'Matrices Magiques',
    filePath: 'games/12-matrices-magiques/screens/MatricesVictoryScreen.tsx',
    component: MatricesVictoryScreen,
    defaultProps: {},
    description: 'MatricesVictoryScreen component',
  },
  {
    id: 'matrices-magiques---choices-choice-button',
    name: 'ChoiceButton',
    category: 'Matrices Magiques - Choices',
    filePath: 'games/12-matrices-magiques/components/choices/ChoiceButton.tsx',
    component: ChoiceButton,
    defaultProps: {},
    description: 'ChoiceButton component',
  },
  {
    id: 'matrices-magiques---choices-choice-panel',
    name: 'ChoicePanel',
    category: 'Matrices Magiques - Choices',
    filePath: 'games/12-matrices-magiques/components/choices/ChoicePanel.tsx',
    component: ChoicePanel,
    defaultProps: {},
    description: 'ChoicePanel component',
  },
  {
    id: 'matrices-magiques---grid-matrix-cell',
    name: 'MatrixCell',
    category: 'Matrices Magiques - Grid',
    filePath: 'games/12-matrices-magiques/components/grid/MatrixCell.tsx',
    component: MatrixCell,
    defaultProps: {},
    description: 'MatrixCell component',
  },
  {
    id: 'matrices-magiques---grid-matrix-grid',
    name: 'MatrixGrid',
    category: 'Matrices Magiques - Grid',
    filePath: 'games/12-matrices-magiques/components/grid/MatrixGrid.tsx',
    component: MatrixGrid,
    defaultProps: {},
    description: 'MatrixGrid component',
  },
  {
    id: 'matrices-magiques---mascot-pixel-mascot',
    name: 'PixelMascot',
    category: 'Matrices Magiques - Mascot',
    filePath: 'games/12-matrices-magiques/components/mascot/PixelMascot.tsx',
    component: PixelMascot,
    defaultProps: {},
    description: 'PixelMascot component',
  },
  {
    id: 'matrices-magiques---mascot-pixel-with-bubble',
    name: 'PixelWithBubble',
    category: 'Matrices Magiques - Mascot',
    filePath: 'games/12-matrices-magiques/components/mascot/PixelWithBubble.tsx',
    component: PixelWithBubble,
    defaultProps: {},
    description: 'PixelWithBubble component',
  },
  {
    id: 'matrices-magiques---mascot-speech-bubble',
    name: 'SpeechBubble',
    category: 'Matrices Magiques - Mascot',
    filePath: 'games/12-matrices-magiques/components/mascot/SpeechBubble.tsx',
    component: SpeechBubble,
    defaultProps: {},
    description: 'SpeechBubble component',
  },
  {
    id: 'matrices-magiques---shapes-shape-renderer',
    name: 'ShapeRenderer',
    category: 'Matrices Magiques - Shapes',
    filePath: 'games/12-matrices-magiques/components/shapes/ShapeRenderer.tsx',
    component: ShapeRenderer,
    defaultProps: {},
    description: 'ShapeRenderer component',
  },
  {
    id: 'matrices-magiques---ui-attempts-display',
    name: 'AttemptsDisplay',
    category: 'Matrices Magiques - Ui',
    filePath: 'games/12-matrices-magiques/components/ui/AttemptsDisplay.tsx',
    component: AttemptsDisplay,
    defaultProps: {},
    description: 'AttemptsDisplay component',
  },
  {
    id: 'matrices-magiques---ui-progress-dots',
    name: 'ProgressDots',
    category: 'Matrices Magiques - Ui',
    filePath: 'games/12-matrices-magiques/components/ui/ProgressDots.tsx',
    component: ProgressDots,
    defaultProps: {},
    description: 'ProgressDots component',
  },
  {
    id: 'matrices-magiques---ui-validate-button',
    name: 'ValidateButton',
    category: 'Matrices Magiques - Ui',
    filePath: 'games/12-matrices-magiques/components/ui/ValidateButton.tsx',
    component: ValidateButton,
    defaultProps: {},
    description: 'ValidateButton component',
  },
  {
    id: 'matrices-magiques---world-world-card',
    name: 'WorldCard',
    category: 'Matrices Magiques - World',
    filePath: 'games/12-matrices-magiques/components/world/WorldCard.tsx',
    component: WorldCard,
    defaultProps: {},
    description: 'WorldCard component',
  },
  {
    id: 'matrices-magiques---world-world-selector',
    name: 'WorldSelector',
    category: 'Matrices Magiques - World',
    filePath: 'games/12-matrices-magiques/components/world/WorldSelector.tsx',
    component: WorldSelector,
    defaultProps: {},
    description: 'WorldSelector component',
  },
  {
    id: 'memory-game-board',
    name: 'GameBoard',
    category: 'Memory',
    filePath: 'games/07-memory/components/GameBoard.tsx',
    component: GameBoard$Memory,
    defaultProps: {},
    description: 'GameBoard component',
  },
  {
    id: 'memory-memory-card',
    name: 'MemoryCard',
    category: 'Memory',
    filePath: 'games/07-memory/components/MemoryCard.tsx',
    component: MemoryCard,
    defaultProps: {},
    description: 'MemoryCard component',
  },
  {
    id: 'memory-memory-grid',
    name: 'MemoryGrid',
    category: 'Memory',
    filePath: 'games/07-memory/components/MemoryGrid.tsx',
    component: MemoryGrid,
    defaultProps: {},
    description: 'MemoryGrid component',
  },
  {
    id: 'memory-memory-intro-screen',
    name: 'MemoryIntroScreen',
    category: 'Memory',
    filePath: 'games/07-memory/screens/MemoryIntroScreen.tsx',
    component: MemoryIntroScreen,
    defaultProps: {},
    description: 'MemoryIntroScreen component',
  },
  {
    id: 'memory---mascot-memo-mascot',
    name: 'MemoMascot',
    category: 'Memory - Mascot',
    filePath: 'games/07-memory/components/mascot/MemoMascot.tsx',
    component: MemoMascot,
    defaultProps: {},
    description: 'MemoMascot component',
  },
  {
    id: 'mots-croises-clue-list',
    name: 'ClueList',
    category: 'Mots Croises',
    filePath: 'games/10-mots-croises/components/ClueList.tsx',
    component: ClueList,
    defaultProps: {},
    description: 'ClueList component',
  },
  {
    id: 'mots-croises-crossword-cell',
    name: 'CrosswordCell',
    category: 'Mots Croises',
    filePath: 'games/10-mots-croises/components/CrosswordCell.tsx',
    component: CrosswordCell,
    defaultProps: {},
    description: 'CrosswordCell component',
  },
  {
    id: 'mots-croises-crossword-grid',
    name: 'CrosswordGrid',
    category: 'Mots Croises',
    filePath: 'games/10-mots-croises/components/CrosswordGrid.tsx',
    component: CrosswordGrid,
    defaultProps: {},
    description: 'CrosswordGrid component',
  },
  {
    id: 'mots-croises-game-board',
    name: 'GameBoard',
    category: 'Mots Croises',
    filePath: 'games/10-mots-croises/components/GameBoard.tsx',
    component: GameBoard$MotsCroises,
    defaultProps: {},
    description: 'GameBoard component',
  },
  {
    id: 'mots-croises-keyboard',
    name: 'Keyboard',
    category: 'Mots Croises',
    filePath: 'games/10-mots-croises/components/Keyboard.tsx',
    component: Keyboard,
    defaultProps: {},
    description: 'Keyboard component',
  },
  {
    id: 'mots-croises-lexie-mascot',
    name: 'LexieMascot',
    category: 'Mots Croises',
    filePath: 'games/10-mots-croises/components/LexieMascot.tsx',
    component: LexieMascot,
    defaultProps: {},
    description: 'LexieMascot component',
  },
  {
    id: 'mots-croises-mots-croises-intro-screen',
    name: 'MotsCroisesIntroScreen',
    category: 'Mots Croises',
    filePath: 'games/10-mots-croises/screens/MotsCroisesIntroScreen.tsx',
    component: MotsCroisesIntroScreen,
    defaultProps: {},
    description: 'MotsCroisesIntroScreen component',
  },
  {
    id: 'other-home-screen-v10',
    name: 'HomeScreenV10',
    category: 'Other',
    filePath: 'screens/HomeScreenV10.tsx',
    component: HomeScreenV10,
    defaultProps: {},
    description: 'HomeScreenV10 component',
  },
  {
    id: 'parent-activity-timeline',
    name: 'ActivityTimeline',
    category: 'Parent',
    filePath: 'components/parent/ActivityTimeline.tsx',
    component: ActivityTimeline,
    defaultProps: {},
    description: 'ActivityTimeline component',
  },
  {
    id: 'parent-badges-gallery',
    name: 'BadgesGallery',
    category: 'Parent',
    filePath: 'components/parent/BadgesGallery.tsx',
    component: BadgesGallery,
    defaultProps: {},
    description: 'BadgesGallery component',
  },
  {
    id: 'parent-badges-section',
    name: 'BadgesSection',
    category: 'Parent',
    filePath: 'components/parent/BadgesGallery.tsx',
    component: BadgesSection,
    defaultProps: {},
    description: 'BadgesSection component',
  },
  {
    id: 'parent-behavior-insights',
    name: 'BehaviorInsights',
    category: 'Parent',
    filePath: 'components/parent/BehaviorInsights.tsx',
    component: BehaviorInsights,
    defaultProps: {},
    description: 'BehaviorInsights component',
  },
  {
    id: 'parent-child-selector',
    name: 'ChildSelector',
    category: 'Parent',
    filePath: 'components/parent/ChildSelector.tsx',
    component: ChildSelector,
    defaultProps: {},
    description: 'ChildSelector component',
  },
  {
    id: 'parent-goal-editor',
    name: 'GoalEditor',
    category: 'Parent',
    filePath: 'components/parent/GoalEditor.tsx',
    component: GoalEditor,
    defaultProps: {},
    description: 'GoalEditor component',
  },
  {
    id: 'parent-goals-section',
    name: 'GoalsSection',
    category: 'Parent',
    filePath: 'components/parent/GoalsSection.tsx',
    component: GoalsSection,
    defaultProps: {},
    description: 'GoalsSection component',
  },
  {
    id: 'parent-parent-dashboard',
    name: 'ParentDashboard',
    category: 'Parent',
    filePath: 'components/parent/ParentDashboard.tsx',
    component: ParentDashboard,
    defaultProps: {},
    description: 'ParentDashboard component',
  },
  {
    id: 'parent-parent-drawer',
    name: 'ParentDrawer',
    category: 'Parent',
    filePath: 'components/parent/ParentDrawer.tsx',
    component: ParentDrawer,
    defaultProps: {},
    description: 'ParentDrawer component',
  },
  {
    id: 'parent-parent-tabs',
    name: 'ParentTabs',
    category: 'Parent',
    filePath: 'components/parent/ParentTabs.tsx',
    component: ParentTabs,
    defaultProps: {},
    description: 'ParentTabs component',
  },
  {
    id: 'parent-parent-zone',
    name: 'ParentZone',
    category: 'Parent',
    filePath: 'components/parent/ParentZone.tsx',
    component: ParentZone,
    defaultProps: {},
    description: 'ParentZone component',
  },
  {
    id: 'parent-progress-chart',
    name: 'ProgressChart',
    category: 'Parent',
    filePath: 'components/parent/ProgressChart.tsx',
    component: ProgressChart,
    defaultProps: {},
    description: 'ProgressChart component',
  },
  {
    id: 'parent-recommendations-card',
    name: 'RecommendationsCard',
    category: 'Parent',
    filePath: 'components/parent/RecommendationsCard.tsx',
    component: RecommendationsCard,
    defaultProps: {},
    description: 'RecommendationsCard component',
  },
  {
    id: 'parent-screen-time-card',
    name: 'ScreenTimeCard',
    category: 'Parent',
    filePath: 'components/parent/ScreenTimeCard.tsx',
    component: ScreenTimeCard,
    defaultProps: {},
    description: 'ScreenTimeCard component',
  },
  {
    id: 'parent-skills-radar',
    name: 'SkillsRadar',
    category: 'Parent',
    filePath: 'components/parent/SkillsRadar.tsx',
    component: SkillsRadar,
    defaultProps: {},
    description: 'SkillsRadar component',
  },
  {
    id: 'parent-skills-radar-v2',
    name: 'SkillsRadarV2',
    category: 'Parent',
    filePath: 'components/parent/SkillsRadarV2.tsx',
    component: SkillsRadarV2,
    defaultProps: {},
    description: 'SkillsRadarV2 component',
  },
  {
    id: 'parent-strengths-card',
    name: 'StrengthsCard',
    category: 'Parent',
    filePath: 'components/parent/StrengthsCard.tsx',
    component: StrengthsCard,
    defaultProps: {},
    description: 'StrengthsCard component',
  },
  {
    id: 'parent-weekly-chart',
    name: 'WeeklyChart',
    category: 'Parent',
    filePath: 'components/parent/WeeklyChart.tsx',
    component: WeeklyChart,
    defaultProps: {},
    description: 'WeeklyChart component',
  },
  {
    id: 'sudoku-felix-mascot',
    name: 'FelixMascot',
    category: 'Sudoku',
    filePath: 'games/05-sudoku/components/FelixMascot.tsx',
    component: FelixMascot,
    defaultProps: {},
    description: 'FelixMascot component',
  },
  {
    id: 'sudoku-floating-action-buttons',
    name: 'FloatingActionButtons',
    category: 'Sudoku',
    filePath: 'games/05-sudoku/components/FloatingActionButtons.tsx',
    component: FloatingActionButtons,
    defaultProps: {},
    description: 'FloatingActionButtons component',
  },
  {
    id: 'sudoku-game-timer',
    name: 'GameTimer',
    category: 'Sudoku',
    filePath: 'games/05-sudoku/components/GameTimer.tsx',
    component: GameTimer,
    defaultProps: {},
    description: 'GameTimer component',
  },
  {
    id: 'sudoku-library-decoration',
    name: 'LibraryDecoration',
    category: 'Sudoku',
    filePath: 'games/05-sudoku/components/LibraryDecoration.tsx',
    component: LibraryDecoration,
    defaultProps: {},
    description: 'LibraryDecoration component',
  },
  {
    id: 'sudoku-progress-bar',
    name: 'ProgressBar',
    category: 'Sudoku',
    filePath: 'games/05-sudoku/components/ProgressBar.tsx',
    component: ProgressBar$Sudoku,
    defaultProps: {},
    description: 'ProgressBar component',
  },
  {
    id: 'sudoku-stats-panel',
    name: 'StatsPanel',
    category: 'Sudoku',
    filePath: 'games/05-sudoku/components/StatsPanel.tsx',
    component: StatsPanel,
    defaultProps: {},
    description: 'StatsPanel component',
  },
  {
    id: 'sudoku-sudoku-background',
    name: 'SudokuBackground',
    category: 'Sudoku',
    filePath: 'games/05-sudoku/components/SudokuBackground.tsx',
    component: SudokuBackground,
    defaultProps: {},
    description: 'SudokuBackground component',
  },
  {
    id: 'sudoku-sudoku-cell',
    name: 'SudokuCell',
    category: 'Sudoku',
    filePath: 'games/05-sudoku/components/SudokuCell.tsx',
    component: SudokuCell,
    defaultProps: {},
    description: 'SudokuCell component',
  },
  {
    id: 'sudoku-sudoku-game-area',
    name: 'SudokuGameArea',
    category: 'Sudoku',
    filePath: 'games/05-sudoku/components/SudokuGameArea.tsx',
    component: SudokuGameArea,
    defaultProps: {},
    description: 'SudokuGameArea component',
  },
  {
    id: 'sudoku-sudoku-grid',
    name: 'SudokuGrid',
    category: 'Sudoku',
    filePath: 'games/05-sudoku/components/SudokuGrid.tsx',
    component: SudokuGrid,
    defaultProps: {},
    description: 'SudokuGrid component',
  },
  {
    id: 'sudoku-sudoku-intro-screen',
    name: 'SudokuIntroScreen',
    category: 'Sudoku',
    filePath: 'games/05-sudoku/screens/SudokuIntroScreen.tsx',
    component: SudokuIntroScreen,
    defaultProps: {},
    description: 'SudokuIntroScreen component',
  },
  {
    id: 'sudoku-sudoku-level-card',
    name: 'SudokuLevelCard',
    category: 'Sudoku',
    filePath: 'games/05-sudoku/components/SudokuLevelCard.tsx',
    component: SudokuLevelCard,
    defaultProps: {},
    description: 'SudokuLevelCard component',
  },
  {
    id: 'sudoku-sudoku-progress-panel',
    name: 'SudokuProgressPanel',
    category: 'Sudoku',
    filePath: 'games/05-sudoku/components/SudokuProgressPanel.tsx',
    component: SudokuProgressPanel,
    defaultProps: {},
    description: 'SudokuProgressPanel component',
  },
  {
    id: 'sudoku-symbol-selector',
    name: 'SymbolSelector',
    category: 'Sudoku',
    filePath: 'games/05-sudoku/components/SymbolSelector.tsx',
    component: SymbolSelector,
    defaultProps: {},
    description: 'SymbolSelector component',
  },
  {
    id: 'sudoku-training-mode-selector',
    name: 'TrainingModeSelector',
    category: 'Sudoku',
    filePath: 'games/05-sudoku/components/TrainingModeSelector.tsx',
    component: TrainingModeSelector,
    defaultProps: {},
    description: 'TrainingModeSelector component',
  },
  {
    id: 'suites-logiques-choice-panel',
    name: 'ChoicePanel',
    category: 'Suites Logiques',
    filePath: 'games/02-suites-logiques/components/ChoicePanel.tsx',
    component: ChoicePanel$SuitesLogiques,
    defaultProps: {},
    description: 'ChoicePanel component',
  },
  {
    id: 'suites-logiques-mascot-robot',
    name: 'MascotRobot',
    category: 'Suites Logiques',
    filePath: 'games/02-suites-logiques/components/MascotRobot.tsx',
    component: MascotRobot,
    defaultProps: {},
    description: 'MascotRobot component',
  },
  {
    id: 'suites-logiques-missing-slot',
    name: 'MissingSlot',
    category: 'Suites Logiques',
    filePath: 'games/02-suites-logiques/components/MissingSlot.tsx',
    component: MissingSlot,
    defaultProps: {},
    description: 'MissingSlot component',
  },
  {
    id: 'suites-logiques-sequence-display',
    name: 'SequenceDisplay',
    category: 'Suites Logiques',
    filePath: 'games/02-suites-logiques/components/SequenceDisplay.tsx',
    component: SequenceDisplay,
    defaultProps: {},
    description: 'SequenceDisplay component',
  },
  {
    id: 'suites-logiques-sequence-element',
    name: 'SequenceElement',
    category: 'Suites Logiques',
    filePath: 'games/02-suites-logiques/components/SequenceElement.tsx',
    component: SequenceElement,
    defaultProps: {},
    description: 'SequenceElement component',
  },
  {
    id: 'suites-logiques-suites-intro-screen',
    name: 'SuitesIntroScreen',
    category: 'Suites Logiques',
    filePath: 'games/02-suites-logiques/screens/SuitesIntroScreen.tsx',
    component: SuitesIntroScreen,
    defaultProps: {},
    description: 'SuitesIntroScreen component',
  },
  {
    id: 'suites-logiques-suites-logiques-game',
    name: 'SuitesLogiquesGame',
    category: 'Suites Logiques',
    filePath: 'games/02-suites-logiques/components/SuitesLogiquesGame.tsx',
    component: SuitesLogiquesGame,
    defaultProps: {},
    description: 'SuitesLogiquesGame component',
  },
  {
    id: 'suites-logiques---svg-alien-svg',
    name: 'AlienSVG',
    category: 'Suites Logiques - Svg',
    filePath: 'games/02-suites-logiques/components/svg/SpaceElements.tsx',
    component: AlienSVG,
    defaultProps: {},
    description: 'AlienSVG component',
  },
  {
    id: 'suites-logiques---svg-chicken-svg',
    name: 'ChickenSVG',
    category: 'Suites Logiques - Svg',
    filePath: 'games/02-suites-logiques/components/svg/FarmAnimals.tsx',
    component: ChickenSVG,
    defaultProps: {},
    description: 'ChickenSVG component',
  },
  {
    id: 'suites-logiques---svg-circle-svg',
    name: 'CircleSVG',
    category: 'Suites Logiques - Svg',
    filePath: 'games/02-suites-logiques/components/svg/GeometricShapes.tsx',
    component: CircleSVG,
    defaultProps: {},
    description: 'CircleSVG component',
  },
  {
    id: 'suites-logiques---svg-clef-svg',
    name: 'ClefSVG',
    category: 'Suites Logiques - Svg',
    filePath: 'games/02-suites-logiques/components/svg/MusicElements.tsx',
    component: ClefSVG,
    defaultProps: {},
    description: 'ClefSVG component',
  },
  {
    id: 'suites-logiques---svg-cow-svg',
    name: 'CowSVG',
    category: 'Suites Logiques - Svg',
    filePath: 'games/02-suites-logiques/components/svg/FarmAnimals.tsx',
    component: CowSVG,
    defaultProps: {},
    description: 'CowSVG component',
  },
  {
    id: 'suites-logiques---svg-diamond-svg',
    name: 'DiamondSVG',
    category: 'Suites Logiques - Svg',
    filePath: 'games/02-suites-logiques/components/svg/GeometricShapes.tsx',
    component: DiamondSVG,
    defaultProps: {},
    description: 'DiamondSVG component',
  },
  {
    id: 'suites-logiques---svg-double-note-svg',
    name: 'DoubleNoteSVG',
    category: 'Suites Logiques - Svg',
    filePath: 'games/02-suites-logiques/components/svg/MusicElements.tsx',
    component: DoubleNoteSVG,
    defaultProps: {},
    description: 'DoubleNoteSVG component',
  },
  {
    id: 'suites-logiques---svg-drum-svg',
    name: 'DrumSVG',
    category: 'Suites Logiques - Svg',
    filePath: 'games/02-suites-logiques/components/svg/MusicElements.tsx',
    component: DrumSVG,
    defaultProps: {},
    description: 'DrumSVG component',
  },
  {
    id: 'suites-logiques---svg-horse-svg',
    name: 'HorseSVG',
    category: 'Suites Logiques - Svg',
    filePath: 'games/02-suites-logiques/components/svg/FarmAnimals.tsx',
    component: HorseSVG,
    defaultProps: {},
    description: 'HorseSVG component',
  },
  {
    id: 'suites-logiques---svg-moon-svg',
    name: 'MoonSVG',
    category: 'Suites Logiques - Svg',
    filePath: 'games/02-suites-logiques/components/svg/SpaceElements.tsx',
    component: MoonSVG,
    defaultProps: {},
    description: 'MoonSVG component',
  },
  {
    id: 'suites-logiques---svg-note-svg',
    name: 'NoteSVG',
    category: 'Suites Logiques - Svg',
    filePath: 'games/02-suites-logiques/components/svg/MusicElements.tsx',
    component: NoteSVG,
    defaultProps: {},
    description: 'NoteSVG component',
  },
  {
    id: 'suites-logiques---svg-pig-svg',
    name: 'PigSVG',
    category: 'Suites Logiques - Svg',
    filePath: 'games/02-suites-logiques/components/svg/FarmAnimals.tsx',
    component: PigSVG,
    defaultProps: {},
    description: 'PigSVG component',
  },
  {
    id: 'suites-logiques---svg-planet-svg',
    name: 'PlanetSVG',
    category: 'Suites Logiques - Svg',
    filePath: 'games/02-suites-logiques/components/svg/SpaceElements.tsx',
    component: PlanetSVG,
    defaultProps: {},
    description: 'PlanetSVG component',
  },
  {
    id: 'suites-logiques---svg-rocket-svg',
    name: 'RocketSVG',
    category: 'Suites Logiques - Svg',
    filePath: 'games/02-suites-logiques/components/svg/SpaceElements.tsx',
    component: RocketSVG,
    defaultProps: {},
    description: 'RocketSVG component',
  },
  {
    id: 'suites-logiques---svg-sheep-svg',
    name: 'SheepSVG',
    category: 'Suites Logiques - Svg',
    filePath: 'games/02-suites-logiques/components/svg/FarmAnimals.tsx',
    component: SheepSVG,
    defaultProps: {},
    description: 'SheepSVG component',
  },
  {
    id: 'suites-logiques---svg-square-svg',
    name: 'SquareSVG',
    category: 'Suites Logiques - Svg',
    filePath: 'games/02-suites-logiques/components/svg/GeometricShapes.tsx',
    component: SquareSVG,
    defaultProps: {},
    description: 'SquareSVG component',
  },
  {
    id: 'suites-logiques---svg-staff-note-svg',
    name: 'StaffNoteSVG',
    category: 'Suites Logiques - Svg',
    filePath: 'games/02-suites-logiques/components/svg/MusicElements.tsx',
    component: StaffNoteSVG,
    defaultProps: {},
    description: 'StaffNoteSVG component',
  },
  {
    id: 'suites-logiques---svg-star-space-svg',
    name: 'StarSpaceSVG',
    category: 'Suites Logiques - Svg',
    filePath: 'games/02-suites-logiques/components/svg/SpaceElements.tsx',
    component: StarSpaceSVG,
    defaultProps: {},
    description: 'StarSpaceSVG component',
  },
  {
    id: 'suites-logiques---svg-star-svg',
    name: 'StarSVG',
    category: 'Suites Logiques - Svg',
    filePath: 'games/02-suites-logiques/components/svg/GeometricShapes.tsx',
    component: StarSVG,
    defaultProps: {},
    description: 'StarSVG component',
  },
  {
    id: 'suites-logiques---svg-triangle-svg',
    name: 'TriangleSVG',
    category: 'Suites Logiques - Svg',
    filePath: 'games/02-suites-logiques/components/svg/GeometricShapes.tsx',
    component: TriangleSVG,
    defaultProps: {},
    description: 'TriangleSVG component',
  },
  {
    id: 'tangram-shadow-shape',
    name: 'ShadowShape',
    category: 'Tangram',
    filePath: 'games/08-tangram/components/ShadowShape.tsx',
    component: ShadowShape,
    defaultProps: {},
    description: 'ShadowShape component',
  },
  {
    id: 'tangram-tangram-board',
    name: 'TangramBoard',
    category: 'Tangram',
    filePath: 'games/08-tangram/components/TangramBoard.tsx',
    component: TangramBoard,
    defaultProps: {},
    description: 'TangramBoard component',
  },
  {
    id: 'tangram-tangram-piece',
    name: 'TangramPiece',
    category: 'Tangram',
    filePath: 'games/08-tangram/components/TangramPiece.tsx',
    component: TangramPiece,
    defaultProps: {},
    description: 'TangramPiece component',
  }
];

// ============================================================
// HELPER FUNCTIONS
// ============================================================
export const getComponentById = (id: string): PlaygroundComponent | undefined => {
  return COMPONENT_REGISTRY.find((c) => c.id === id);
};

export const getComponentsByCategory = (category: string): PlaygroundComponent[] => {
  return COMPONENT_REGISTRY.filter((c) => c.category === category);
};

export const getAllCategories = (): string[] => {
  const categories = new Set(COMPONENT_REGISTRY.map((c) => c.category));
  return Array.from(categories).sort();
};

export const searchComponents = (query: string): PlaygroundComponent[] => {
  const q = query.toLowerCase();
  return COMPONENT_REGISTRY.filter(
    (c) =>
      c.name.toLowerCase().includes(q) ||
      c.category.toLowerCase().includes(q) ||
      c.description?.toLowerCase().includes(q)
  );
};
