/**
 * Game registry
 * Central catalog of all available games
 */

import type { GameMetadata } from '@/types';

export const gameRegistry: GameMetadata[] = [
  {
    id: 'hanoi',
    name: 'Tour de Hanoï',
    nameKey: 'games.hanoi.name',
    description: 'Déplace les disques d\'une tour à l\'autre',
    descriptionKey: 'games.hanoi.description',
    icon: null,
    minAge: 6,
    maxAge: 10,
    category: 'logic',
    skills: ['planning', 'problem_solving', 'sequencing', 'perseverance'],
    status: 'available',
    route: '/(games)/hanoi',
  },
  {
    id: 'math-blocks',
    name: 'MathBlocks',
    nameKey: 'games.mathblocks.name',
    description: 'Associe les calculs avec leurs résultats',
    descriptionKey: 'games.mathblocks.description',
    icon: null,
    minAge: 5,
    maxAge: 12,
    category: 'math',
    skills: ['concentration', 'problem_solving', 'pattern_recognition'],
    status: 'available',
    route: '/(games)/math-blocks',
  },
  {
    id: 'sudoku',
    name: 'Sudoku Montessori',
    nameKey: 'games.sudoku.name',
    description: 'Complète la grille avec logique',
    descriptionKey: 'games.sudoku.description',
    icon: null,
    minAge: 6,
    maxAge: 10,
    category: 'logic',
    skills: ['deductive_reasoning', 'concentration', 'patience', 'systematic_thinking'],
    status: 'available',
    route: '/(games)/sudoku',
  },
  {
    id: 'suites-logiques',
    name: 'Suites Logiques',
    nameKey: 'games.suiteslogiques.name',
    description: 'Découvre les motifs et complète les suites',
    descriptionKey: 'games.suiteslogiques.description',
    icon: null,
    minAge: 6,
    maxAge: 10,
    category: 'logic',
    skills: ['pattern_recognition', 'deductive_reasoning', 'sequencing', 'problem_solving'],
    status: 'available',
    route: '/(games)/suites-logiques',
  },
  {
    id: 'logix-grid',
    name: 'Logix Grid',
    nameKey: 'games.logixgrid.name',
    description: 'Résous des puzzles logiques avec des indices',
    descriptionKey: 'games.logixgrid.description',
    icon: null,
    minAge: 7,
    maxAge: 10,
    category: 'logic',
    skills: ['deductive_reasoning', 'systematic_thinking', 'concentration', 'problem_solving'],
    status: 'available',
    route: '/(games)/logix-grid',
  },
  {
    id: 'memory',
    name: 'Memory',
    nameKey: 'games.memory.name',
    description: 'Trouve les paires d\'images',
    descriptionKey: 'games.memory.description',
    icon: null,
    minAge: 5,
    maxAge: 8,
    category: 'memory',
    skills: ['working_memory', 'concentration', 'pattern_recognition'],
    status: 'available',
    route: '/(games)/memory',
  },
  {
    id: 'tangram',
    name: 'Puzzle Formes',
    nameKey: 'games.tangram.name',
    description: 'Assemble les pièces géométriques pour créer des formes',
    descriptionKey: 'games.tangram.description',
    icon: null,
    minAge: 6,
    maxAge: 10,
    category: 'spatial',
    skills: ['spatial_reasoning', 'problem_solving', 'pattern_recognition', 'concentration'],
    status: 'available',
    route: '/(games)/tangram',
  },
  {
    id: 'labyrinthe',
    name: 'Labyrinthe',
    nameKey: 'games.labyrinthe.name',
    description: 'Trouve ton chemin vers la sortie',
    descriptionKey: 'games.labyrinthe.description',
    icon: null,
    minAge: 6,
    maxAge: 10,
    category: 'spatial',
    skills: ['planning', 'spatial_reasoning', 'problem_solving', 'perseverance'],
    status: 'available',
    route: '/labyrinthe-demo',
  },
  {
    id: 'balance',
    name: 'Balance Logique',
    nameKey: 'games.balance.name',
    description: 'Équilibre la balance en découvrant les équivalences',
    descriptionKey: 'games.balance.description',
    icon: null,
    minAge: 6,
    maxAge: 10,
    category: 'logic',
    skills: ['quantitative_reasoning', 'equivalence', 'problem_solving', 'pre_algebra'],
    status: 'available',
    route: '/(games)/balance',
  },
  {
    id: 'mots-croises',
    name: 'Mots Croisés',
    nameKey: 'games.motscroises.name',
    description: 'Complète la grille avec les bons mots',
    descriptionKey: 'games.motscroises.description',
    icon: null,
    minAge: 7,
    maxAge: 10,
    category: 'language',
    skills: ['vocabulary', 'spelling', 'deductive_reasoning', 'concentration'],
    status: 'available',
    route: '/(games)/mots-croises',
  },
  {
    id: 'conteur-curieux',
    name: 'Le Conteur Curieux',
    nameKey: 'games.conteurcurieux.name',
    description: 'Lis des histoires et réponds aux questions',
    descriptionKey: 'games.conteurcurieux.description',
    icon: null,
    minAge: 6,
    maxAge: 10,
    category: 'language',
    skills: ['reading_comprehension', 'vocabulary', 'memory', 'inference'],
    status: 'available',
    route: '/(games)/conteur-curieux',
  },
  {
    id: 'matrices-magiques',
    name: 'Matrices Magiques',
    nameKey: 'games.matricesmagiques.name',
    description: 'Découvre les motifs et complète les matrices',
    descriptionKey: 'games.matricesmagiques.description',
    icon: null,
    minAge: 7,
    maxAge: 10,
    category: 'logic',
    skills: ['pattern_recognition', 'visual_reasoning', 'logical_thinking', 'concentration'],
    status: 'coming_soon',
    route: '/(games)/matrices-magiques',
  },
];

export const getGameById = (id: string): GameMetadata | undefined => {
  return gameRegistry.find((game) => game.id === id);
};

export const getAvailableGames = (): GameMetadata[] => {
  return gameRegistry.filter((game) => game.status === 'available');
};
